CC      = gcc
CFLAGS  += -std=c99 -g -Wall
CPPFLAGS+= -I.

TARGETS := day1 day2 day3 day4 day5 day6 day7 day8 day9 day10 day11 day12 day13 day14 day15 day16 day17 day18 day19 day20 day21 day22 day23 day24 day25

all: $(TARGETS)
	./day1 /simple-input/day1.in --log
	./day1 /final-input/day1.in
	./day2 /simple-input/day2.in --log
	./day2 /final-input/day2.in
	./day3 /simple-input/day3.in --log
	./day3 /final-input/day3.in
	./day4 /simple-input/day4.in --log
	./day4 /final-input/day4.in
	./day5 /simple-input/day5.in --log
	./day5 /final-input/day5.in
	./day6 /simple-input/day6.in --log
	./day6 /final-input/day6.in
	./day7 /simple-input/day7.in --log
	./day7 /final-input/day7.in
	./day8 /simple-input/day8.in --log
	./day8 /final-input/day8.in
	./day9 /simple-input/day9.in --log
	./day9 /final-input/day9.in
	./day10 /simple-input/day10.in --log
	./day10 /final-input/day10.in
	./day11 /simple-input/day11.in --log
	./day11 /final-input/day11.in
	./day12 /simple-input/day12.in --log
	./day12 /final-input/day12.in
	./day13 /simple-input/day13.in --log
	./day13 /final-input/day13.in
	./day14 /simple-input/day14.in --log
	./day14 /final-input/day14.in
	./day15 /simple-input/day15.in --log
	./day15 /final-input/day15.in
	./day16 /simple-input/day16.in --log
	./day16 /final-input/day16.in
	./day17 /simple-input/day17.in --log
	./day17 /final-input/day17.in
	./day18 /simple-input/day18.in --log
	./day18 /final-input/day18.in
	./day19 /simple-input/day19.in --log
	./day19 /final-input/day19.in
	./day20 /simple-input/day20.in --log
	./day20 /final-input/day20.in
	./day21 /simple-input/day21.in --log
	./day21 /final-input/day21.in
	./day22 /simple-input/day22.in --log
	./day22 /final-input/day22.in
	./day23 /simple-input/day23.in --log
	./day23 /final-input/day23.in
	./day24 /simple-input/day24.in --log
	./day24 /final-input/day24.in
	./day25 /simple-input/day25.in --log
	./day25 /final-input/day25.in


clean:
	rm -rf $(TARGETS)
